sudo: required
git:
  submodules: false
services:
- docker
before_install:
- git clone https://github.com/jacktenor/dbp -b master dbp/
- cd DualBootPatcher && git submodule init && git submodule update && cd ../
- docker pull silverx2222/dualbootpatcher:9.3.0-14-base
- docker pull silverx2222/dualbootpatcher:9.3.0-14-mingw
script:
- mkdir $HOME/.android
- mkdir -p ${TRAVIS_BUILD_DIR}/dbp/builder/ && cd ${TRAVIS_BUILD_DIR}/dbp/
- "sudo docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v \"$(pwd):/builder/dbp:rw,z\"
  -v \"${HOME}/.android:/builder/.android:rw,z\" silverx2222/dualbootpatcher:9.3.0-14-mingw
  bash << EOF  \ncd ~/dbp/builder\ncmake .. -DMBP_BUILD_TARGET=desktop -DMBP_PORTABLE=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-mingw.cmake && make -j16 && cpack &&  chmod +x dllpack && ./dllpack\n"
after_success: 
before_deploy:
- git config --local user.name jacktenor
- git config --local user.email jacktenor1@gmail.com
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%H%M%S')-dbg}
- git tag $TRAVIS_TAG --force
deploy:
  provider: releases
  api_key:
    secure: u6pu0tWN95E5aMIS2PGCW5PulRNFTwfLmqA5VizsZAuBa0hWyUCUpV4eExGHbGih/0X7o4nGE+8Le9AwaQB+iix93E25NmpIDu4vXGlNIiOV1mgihOPQt4ThSUsJlDdOnWvy9/38cXQWXVZBUBUFtGITEmOD7vjYVbgRJJOe5sJrCBGockLBiqwlAHNqd/eTM7uTLL1UylTgNmCAgctCRW7A1RUWEkKYQKqFTR64fDCWDUXz8EqJLvHr4lzTsXSy30880gUanqJVcv4EDGq/2nia3ZGSEkubueF6N6Q1RAkZVC/9MtaO8Przov0jZClwscQPDO3U1btyercQzeBd7r+ppQUOCt+BbzwrYBv7pwvEbLMjC9U0J4j5vF4IVdCQ35YyUXuTBN3j96m1AROwYtGOGNA2TE/1IokyUiWcIz3LTBHclVPsTFHXfj4YX3cnI7j9Hk8sKcPD4wvDkAlEgRNTC9eF0v+DzarW9qIroZf1yjXFjVtF3kt2aj2DrKeVQd9vKa7UqBjYxF8Rcbl5c4tzOozQtAfpszhPthr9t/AX6EqIa+DXq0rLOOm7IMANlTInNaG4LJIdf8j/GXrSPL26YTnm14xwhfrrIuhx9tdI+MoGK11HTG0OCWgX04suuIFaqxyA8ZCRM8dzE7BGbG+E1xl+JEhTLYn9cTA66io=
  file: "${TRAVIS_BUILD_DIR}/dbp/builder/DualBootPatcher-9.3.0-win32.zip"
  skip_cleanup: true
  on:
    all_branches: true
    repo: jacktenor/dbp

